sudo: false
language: android
jdk: oraclejdk8
before_install:
- export JAVA8_HOME=$JAVA_HOME
- android list sdk --no-ui --all --extended
android:
  components:
  - build-tools-23.0.0
  - android-23
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-support
  - extra-android-m2repository
  - addon-google_apis-google-22
script:
- "./gradlew build -PdisablePreDex -x validateReleaseSignSigning"
notifications:
  hipchat:
    template: '<a href="%{build_url}">%{repository}#%{build_number}</a> (%{branch} - <a href="%{compare_url}">%{commit}</a> : %{author}): %{message}'
    format: html
    rooms:
      secure: WBxrL2ceIAXTtJjXG4Gs/IWX+HVJ1izU1Y5UW7chuJ5w2wBCjoPDsAbsJhkaXbhZWQ5haSbEOJXjGwxbUBWVnKhFihYF7Ozh60kpovbJOYKvc7x3/5HsBAgYK0dKUJj7HCVutps2r3lKCXP9YFoOsDZqQd0dRsmxulteigYxn48=
